### ISSUE TITLE
Language switching is janky

### ISSUE THREAD

**Issue by capablemonkey** [Dwolla/slate#1]
Switching to view a different language on the right hand code section causes the navigation on the left sidebar to be off-set and janky.  (e.g. you're told you're in a different section than the one you're in)

**Comment by capablemonkey** [comment]
Looks like this was fixed in tripit/slate.  Woot!

**Comment by mach-kernel** [comment]
LOL I didn't even know we had this issue open

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Relations Engineer

On Jul 13, 2015, at 15:24, Gordon Zheng <notifications@github.com> wrote:

Looks like this was fixed in tripit/slate. Woot!

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/slate/issues/1#issuecomment-121030055>.
